### ISSUE TITLE
i will love to do copywriting for you 

### ISSUE THREAD

**Issue by hamzeyto** [amit-bhandari/AB-Music-Player#12]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate either here or via email, so I don't have to create issues. Thank you.

**Comment by amit-bhandari** [comment]
Hey man, thank you so much. I am really glad you liked AB Music. Yes you are more than welcome to contribute in any way you can to AB Music. You can fork and update read me and send me pull request. 

If you know any other language than English and can translate English to that language, you can contribute in translating AB Music. :)
