### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by abdulmalikkhan655** [amit-bhandari/AB-Music-Player#13]
Hello, @amit-bhandariI want to contribute in "AB-Music-Player" so i  want to designed a new logo for "AB-Music-Player" and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.
if you want i will send you my design

contact me on facebook for fast delivary

**Comment by ggcarlosr** [comment]
Hello friend, I am also available to join by presenting a logo proposal, and you can have a second option to choose, can I contribute?

**Comment by amit-bhandari** [comment]
You can show your design to me wither here or at Facebook. I have sent you a request. Thanks

**Comment by abdulmalikkhan655** [comment]
ok brother i will show you my logo design  as soon as

**Comment by abdulmalikkhan655** [comment]
![32457503_1866053773439696_3416851139159654400_n](https://user-images.githubusercontent.com/36396753/40056291-583f73ee-5864-11e8-89ec-c50f9bc717cc.jpg)
hello sir check this logo and select your logo If there's something you want to change, I'll do it.

**Comment by abdulmalikkhan655** [comment]
![32659801_586152721764707_897233094929547264_n](https://user-images.githubusercontent.com/36396753/40140416-5059257c-596c-11e8-8142-135868dae16b.jpg)

hello sir check this awesome logo  If there's something you want to change, I'll do it.

**Comment by TacoTheDank** [comment]
an actual logo designer wouldn't provide jpgs as examples, let alone shitty quality jpgs

**Comment by abdulmalikkhan655** [comment]
@TacoTheDank  how are you :PD :D

**Comment by TacoTheDank** [comment]
dead inside
