### ISSUE TITLE
Permission to enable AB music player modify system settings is impossible.

### ISSUE THREAD

**Issue by kodeblacc** [amit-bhandari/AB-Music-Player#15]
#### Expected behavior
AB music player provides an option to set a track as ringtone. On android 7.0+, the expected behavior is, when the option is selected I'll be referred to toggle on the permission which will enable the app modify system(device) settings.
#### Actual behavior
After the set as ringtone option was selected, as usual the prompt to enable the permission popped-up, but the option doesn't get enabled. This seemed like a device issue but several tests on 4 other devices proved otherwise. However on a device running Android 5.0, permissions are not required but selecting the option to set as ringtone first gives and error message and then a successful message but track is not set as device ringtone
#### How to reproduce
- Launch [AB music player](https://github.com/amit-bhandari/AB-Music-Player/releases/download/v8.0/app-release.apk) 
- Accept all the permissions that pop-up on first installation.
- Swipe to track tab and press the 3 dots beside a track to reveal options
- Click on set as ringtone
- Click Okay on the prompt that pops up and you'll be redirected to settings menu to toggle on of off permission to allow modification of system settings.

* App name/App version: AB music player v Version 8
* Operating system: LG V10( Android 7.0) Tecno L8( Android 5.0)

#### Recording Of The Bug
https://youtu.be/UDtwpVuDzX4
Video of test on Android 7.0 Device

https://youtu.be/vfE5OvFzoFQ
Video of test on Android 5.0 Device

**Comment by amit-bhandari** [comment]
Thanks for the bug report. Able to reproduce it. Will look into it.

**Comment by kodeblacc** [comment]
Alright looking forward to it getting fixed

**Comment by amit-bhandari** [comment]
Solved on latest commit on development branch
