### ISSUE TITLE
AB music player: Shake to play next song doesn't work after sleep timer has elapsed and a song was played again.

### ISSUE THREAD

**Issue by kodeblacc** [amit-bhandari/AB-Music-Player#16]
#### Expected behavior
The music player supports the shake gesture to perform an action. The shake gesture is expected to function  at all times irrespective of any other action performed within the premise of the music player.
#### Actual behavior
The shake gesture on AB music player which can perform any three actions did not work after sleep timer that  was set elapsed.
#### How to reproduce
- Launch [AB music player](https://github.com/amit-bhandari/AB-Music-Player/releases/download/v8.0/app-release.apk) 
- Accept all the permissions that pop-up on first installation.
- Access the app's settings easily by swiping from left to right to reveal the left sliding menu
- On the settings menu scroll down to shake and active the shake control(should be active by default) 
- Assign the action that shake will perform
- Go back to music player menu play a track 
- Click on the 3 dots at the top right and select sleeper timer
- After time has elapsed, current song playing will stop
- Play the song again or any other song
- Shake phone to perform shake gesture and it won't work.<hr>
* App name/App version: AB music player v Version 8
* Operating system:  Android 7.0
#### Recording Of The Bug
https://youtu.be/4yqnIsatgRQ

**Comment by amit-bhandari** [comment]
Thanks for the report, I will check the issue.

**Comment by amit-bhandari** [comment]
Solved in latest commit to development branch
