### ISSUE TITLE
App Crashes On Creating A Playlist.

### ISSUE THREAD

**Issue by organik1** [amit-bhandari/AB-Music-Player#18]
This one is weird I tell you. Creating and accessing a playlist with the name "Then" Or "When" crashes the app instantly.
I don't know which other words do this, but these two seem to be having conflict with the app.

Device: Android 6.0 (spread chipset)

**Comment by amit-bhandari** [comment]
Giving one of the Sqlite keyword as playlist name is crashing the app.

List of those words is here --> https://www.sqlite.org/lang_keywords.html

Thanks for the issue, will look into it.

**Comment by organik1** [comment]
Alright! Looking forward to that fix.

**Comment by amit-bhandari** [comment]
Solved on latest release
