### ISSUE TITLE
Can't add songs to playlist using the FAB within the playlist

### ISSUE THREAD

**Issue by organik1** [amit-bhandari/AB-Music-Player#19]
Hello dev.
I believe the floating action button was meant to fish songs for the playlist. Anytime I make use of that feature it opens the library alright, however clicking on a song, plays the song instead.

**Comment by amit-bhandari** [comment]
It's expected behaviour as of now. Clicking on fab just moves to library where you have to add song in playlist by clicking on overflow (3-dot) button.
