### ISSUE TITLE
App can't be installed after downloading

### ISSUE THREAD

**Issue by jubreal** [amit-bhandari/AB-Music-Player#20]
#### Expected behavior       
The app should get installed and   ready for use after the apk file has been downloaded.
 
 
#### Actual behavior       
The app installation failed.
 
 
#### How to reproduce
1.     Download the latest release of the app from github   release  
2.     Try and install the app after successful download   It will be   observed that the app fails to install, hence, the bug.
 
* Browser/App version: app   version 8.0
*Operating system: Android 6.0
 
#### Recording Of The Bug       
https://youtu.be/cRnBcBsK7ts

**Comment by amit-bhandari** [comment]
What is the error you get?

**Comment by jubreal** [comment]
I get "app not installed" message.
I have also updated the report including a video upload so as to get better report on it.

**Comment by amit-bhandari** [comment]
Before installing, make sure you dont have AB Music installed already on device. If it is, uninstall it first and then install again. Let me know

**Comment by amit-bhandari** [comment]
Okay, I can reproduce this, I will check later in the day why it is happening.

**Comment by jubreal** [comment]
I don't have AB music installed previously on my device, this is the first time I'm installing it. I even deleted and downloaded again.

O.k , Nice

**Comment by amit-bhandari** [comment]
Solved.

**Comment by jubreal** [comment]
Thanks
