### ISSUE TITLE
Privacy Policy Document.

### ISSUE THREAD

**Issue by HarryHeights** [amit-bhandari/AB-Music-Player#21]
Hello, I'm Harry. 
I consider your software to have great potentials with all the amazing features it has in stock. I think it would be better with a privacy policy document which I could pen down for you.

The privacy policy document is to allow users of your software know how you collect and use the personal information they part with when they utilize AB music player and how secured is that information. Where that information is transferred to, and also details about third party apps or services. 

If users are aware of this information it'll greatly enhance developer consumer relationship. 

If you could provide those information above, I'd draft the policy document.

**Comment by amit-bhandari** [comment]
Hey Harry. 

Thanks for reaching out.

AB Music does not really collect any information of user, so it does not make sense to create privacy policy document. Let me know your thoughts on that,

**Comment by HarryHeights** [comment]
Well, what my proposal contained was like the most prominent part of a privacy policy document. It contains other things too and if AB music doesn't collect any information it's still a good thing to let users know that you don't. However aside collecting and using personal data, I've used your app to know it requires internet for certain things to function and also it contains links to other websites and third party apps and services. It also has a signup option where users have to log in with their personal mail accounts. So I'm certain AB music collects user data although it may not be externally collected by you.

Here's a sample of a [privacy policy](https://github.com/moezbhatti/qksms/pull/1265/commits/b6a0f1ea91ccbda1c3a07034112a9e0790865e16) document I created for an SMS app.

I'm grateful you replied. If you won't be needing the document, it's no big deal.

Thanks and have a nice day.

**Comment by amit-bhandari** [comment]
What kind of information do you need for creating the document?

**Comment by HarryHeights** [comment]
Well, since you don't collect personal information like most open source apps do. I can get the information I need to create the document because I've utilized the app enough to know some of the technicalities.

Wait, are you considering the idea of the privacy policy?

**Comment by amit-bhandari** [comment]
Yeah, sure why not, you suggested it will be a good idea.

**Comment by HarryHeights** [comment]
Yes it is a good idea. I'll start creating the document straight away. If I need any other information I can get myself, I'll let you know.

**Comment by amit-bhandari** [comment]
Sure, thanks!

**Comment by HarryHeights** [comment]
Hello, I've been really busy all day. I finally had time to create the document and I've made a pull request. Proof read for discrepancies. between the policy and your project and make possible changes or have me make them. 

I normally include an "About Us" section in the policy but I discovered that an About Us document had already been created so it's all good. 

Thanks for allowing me contribute. In case you need any written content, feel free to send me an email nwosaharry@gmail.com.

**Comment by amit-bhandari** [comment]
Looks excellent. Thanks @HarryHeights .

I will merge it in weekend after few corrections.

**Comment by amit-bhandari** [comment]
merged!

**Comment by HarryHeights** [comment]
Seen.. I'm glad I could contribute.
