### ISSUE TITLE
Last version missing on releases page

### ISSUE THREAD

**Issue by IzzySoft** [amit-bhandari/AB-Music-Player#24]
While Playstore reports v9.0, the only tag on the [releases page](https://github.com/amit-bhandari/AB-Music-Player/releases) is v8.0. Could you please add the newest version there as well? Thanks!

**Comment by amit-bhandari** [comment]
Completely forgot about it!
But now I can't upload it as next beta version is already released in console and soon it's gonna be released as v9.1. 
I will upload that release here for sure!
Apologies!

**Comment by IzzySoft** [comment]
Can't you simply take the APK you released on Play and attach that (here, at Github – shouldn't conflict with what you have in the play console)? Please let me know (with an update here) when a new APK was attached – whether it's v9.0 or a newer version.

Thanks!

**Comment by amit-bhandari** [comment]
Yeah, sure. I will do it today!

**Comment by amit-bhandari** [comment]
Done and dusted!

**Comment by IzzySoft** [comment]
Thanks a lot!
