### ISSUE TITLE
У меня готов перевод плеера на русский язык. Нужен?

### ISSUE THREAD

**Issue by leginnn** [amit-bhandari/AB-Music-Player#6]
[values-ru.zip](https://github.com/amit-bhandari/AB-Music-Player/files/1799744/values-ru.zip)

**Comment by amit-bhandari** [comment]
Sure man, that will be very helpful. Let me know once it is finished, I will dispatch update on store and let me know your real name so that I can mention it in contribution page. Thanks

**Comment by leginnn** [comment]
Перевод готов (переведены все важные строки).
Не нужно указывать мое имя, мне слава не нужна)
Мне нужен нормальный плеер, работающий на моем телефоне (Nokia 6 с Oreo).
На текущий момент все плееры болеют:
1. с наушников при двойном нажатии кнопки все плееры переключают треки два раза вперед (аналогично при тройном нажатии - назад) при заблокированном экране (это связано с новой политикой Google относительно фоновых процессов). В случае с api выше 25 имеется встроенный обработчик нажатий кнопок в системе, который рассылает широковещательные оповещения в пользу последних активных приложений. При блокировке вместо кода KEYCODE_HEADSETHOOK автоматически рассылается KEYCODE_MEDIA_NEXT. При этом Google Music работает как положено.
2. через время перестает работать управление встряхиванием, причем встряхивание в большинстве случаев тоже переключает треки два раза вместо одного.
3. интерфейс реально сильно перегружен лишними деталями (Хотелось бы как здесь - https://play.google.com/store/apps/details?id=com.nazarsoroka.musicplayer)
4. практически ни у кого (за редкими исключениями) нет визуализации спектра (а например плеер Eleven умеет показывает его не только внутри экрана "Текущий трек", но и на экране блокировки.
5. ну и у меня еще куча идей, которые проще самому реализовать ;)

А по твоему плееру - не жадничай. Реклама его убьет как и сотни других плееров. Сделай лучше ограниченный функционал и разнеси с платной версией.
К примеру, после последнего обновления использовать я его больше не буду (
Удачи!

**Comment by amit-bhandari** [comment]
Can you please let me understand more which part of AB Music is heavily overloaded with unnecessary details so that I can work on it.

Please let me know why latest update made AB music not usable for you. If it is because of ads, I can give you promo code to remove those.

**Comment by amit-bhandari** [comment]
I will soon update AB Music with Russian text. If possible could you please translate play store description for AB Music as well. It will be very helpful for seo purpose once I make AB music available in Russian Language!

Are you a Android Developer?

**Comment by leginnn** [comment]
Ну, вот, а я только прочитал все эти сообщения... На днях постараюсь актуализировать перевод. Чуть позже отвечу на другие вопросы (интерфейс и реклама).
