### ISSUE TITLE
When Trying To Add Some Features to This App . The Android Studio Shows Error

### ISSUE THREAD

**Issue by IamJithendra** [amit-bhandari/AB-Music-Player#8]
on Trying to Add Some Features and Changes . the build with android studio shows as Error and The Build is Failing . How Can I Overcome This ?

 Is This Build **Passing** or **Failing**  ???

**Comment by amit-bhandari** [comment]
Hey Jithendra, last time I checked, build was passing. Please paste the error screenshot for me to have look at.

**Comment by IamJithendra** [comment]
![capture-20180404-160527](https://user-images.githubusercontent.com/33452200/38302891-ea76d422-3821-11e8-80ba-ef346aa21dcc.png)
![capture-20180404-160613](https://user-images.githubusercontent.com/33452200/38302892-ead2a22a-3821-11e8-8ae6-7c9ed192047e.png)


 **These Are The Errors I am currently Experiencing**

**Comment by IamJithendra** [comment]
@amit-bhandari  Help Needed

**Comment by amit-bhandari** [comment]
Hey Jithendra, apologies for the delay, Been super busy last couple weekends. Will surely get back to you by today EOD.

**Comment by amit-bhandari** [comment]
I tried cloning the repository in my local and did build and everything worked great. I am using Android Studio 3.1, maybe you could try using same studio version as mine.

Or if you can't do that, try changing %d in "not_enough_reward_points_for_batch_lyrics" to %1$d and try with that.

Replace "not_enough_reward_points_for_batch_lyrics" with the string as below and give it a try. Let me know if it works for you

<string name="not_enough_reward_points_for_batch_lyrics">You do not seem to have enough Reward Points for downloading batch lyrics.
            If you choose to start batch lyrics download anyway, download will be skipped as soon as reward points are exhausted.
            \n\n Reward points you have : %1$d \n  Reward points you need : %1$d</string>

**Comment by amit-bhandari** [comment]
Ignore string provided above and try with this

You do not seem to have enough Reward Points for downloading batch lyrics.
If you choose to start batch lyrics download anyway, download will be skipped as soon as reward points are exhausted.
\n\n Reward points you have : %1$d \n Reward points you need : %2$d
